
; "2" and "3" MHz from fullsnes

CartridgeSpeedSlow = 2
CartridgeSpeedFast = 3

CartridgeModeLoROM        = 0
CartridgeModeHiROM        = 1
CartridgeModeLoROMSDD1    = 2
CartridgeModeLoROMSA1     = 3
CartridgeModeExHiROM      = 5
CartridgeModeHiROMSPC7110 = 10

CartridgeTypeROM                       = 0
CartridgeTypeROMRAM                    = 1
CartridgeTypeROMRAMBattery             = 2
CartridgeTypeROMCoprocessor            = 3
CartridgeTypeROMCoprocessorRAM         = 4
CartridgeTypeROMCoprocessorRAMBattery  = 5
CartridgeTypeROMCoprocessorBattery     = 6

CoprocessorDSP    = 0
CoprocessorSFX    = 1
CoprocessorOBC1   = 2
CoprocessorSA1    = 3
CoprocessorOther  = 14
CoprocessorCustom = 15

CartridgeSubtypeSPC7110 = 0
CartridgeSubtypeST010   = 1
CartridgeSubtypeST011   = 1
CartridgeSubtypeST018   = 2
CartridgeSubtypeCX4     = 16

DestinationJapanese      = (0,  "J")
DestinationNorthAmerican = (1,  "E")
DestinationEurope        = (2,  "P")
DestinationScandinavian  = (3,  "W")
DestinationFinnish       = (4,  None)
DestinationDanish        = (5,  None)
DestinationFrench        = (6,  "F")
DestinationDutch         = (7,  "H")
DestinationSpanish       = (8,  "S")
DestinationGerman        = (9,  "D")
DestinationItalian       = (10, "I")
DestinationChinese       = (11, "C")
DestinationIndonesian    = (12, None)
DestinationSouthKorean   = (13, "K")
DestinationCommon        = (14, "A")
DestinationCanadian      = (15, "N")
DestinationBrazilian     = (16, "B")
DestinationAustralian    = (17, "U")
DestinationOther1        = (18, "X")
DestinationOther2        = (19, "Y")
DestinationOther3        = (20, "Z")
