

	TypeSword   = 00
	TypeLance   = 01
	TypeAxe     = 02
	TypeBow     = 03
	TypeStaff   = 04
	TypeFire    = 05
	TypeThunder = 06
	TypeWind    = 07
	TypeLight   = 08
	TypeDark    = 09

	TypeItem    = 11

	WeaponRankIncrement = 50

	RankE = WeaponRankIncrement * 1
	RankD = WeaponRankIncrement * 2
	RankC = WeaponRankIncrement * 3
	RankB = WeaponRankIncrement * 4
	RankA = WeaponRankIncrement * 5

	TraitBallista     = %00000001 ; $01
	TraitMagicRanged  = %00000010 ; $02
	TraitWeapon       = %00000100 ; $04
	TraitTome         = %00001000 ; $08
	TraitStaff        = %00010000 ; $10
	TraitUnbreakable  = %00100000 ; $20
	TraitUnsellable   = %01000000 ; $40
	TraitBroken       = %10000000 ; $80
