
ObjectiveMarkerRight = aObjectiveMarkerArrowSpriteTable._Right - aObjectiveMarkerArrowSpriteTable
ObjectiveMarkerLeft  = aObjectiveMarkerArrowSpriteTable._Left - aObjectiveMarkerArrowSpriteTable
ObjectiveMarkerUp    = aObjectiveMarkerArrowSpriteTable._Up - aObjectiveMarkerArrowSpriteTable
ObjectiveMarkerDown  = aObjectiveMarkerArrowSpriteTable._Down - aObjectiveMarkerArrowSpriteTable

ObjectiveMarkerRed     = 1
ObjectiveMarkerBlue    = 2
ObjectiveMarkerUnknown = 3
