
aChapterDataPointers ; 84/8000
  .addr Chapter1ChapterDataChapterDataTableEntry
  .addr Chapter2ChapterDataChapterDataTableEntry
  .addr Chapter2xChapterDataChapterDataTableEntry
  .addr Chapter3ChapterDataChapterDataTableEntry
  .addr Chapter4ChapterDataChapterDataTableEntry
  .addr Chapter4xChapterDataChapterDataTableEntry
  .addr Chapter5ChapterDataChapterDataTableEntry
  .addr Chapter6ChapterDataChapterDataTableEntry
  .addr Chapter7ChapterDataChapterDataTableEntry
  .addr Chapter8ChapterDataChapterDataTableEntry
  .addr Chapter8xChapterDataChapterDataTableEntry
  .addr Chapter9ChapterDataChapterDataTableEntry
  .addr Chapter10ChapterDataChapterDataTableEntry
  .addr Chapter11ChapterDataChapterDataTableEntry
  .addr Chapter11xChapterDataChapterDataTableEntry
  .addr Chapter12ChapterDataChapterDataTableEntry
  .addr Chapter12xChapterDataChapterDataTableEntry
  .addr Chapter13ChapterDataChapterDataTableEntry
  .addr Chapter14ChapterDataChapterDataTableEntry
  .addr Chapter14xChapterDataChapterDataTableEntry
  .addr Chapter15ChapterDataChapterDataTableEntry
  .addr Chapter16AChapterDataChapterDataTableEntry
  .addr Chapter17AChapterDataChapterDataTableEntry
  .addr Chapter16BChapterDataChapterDataTableEntry
  .addr Chapter17BChapterDataChapterDataTableEntry
  .addr Chapter18ChapterDataChapterDataTableEntry
  .addr Chapter19ChapterDataChapterDataTableEntry
  .addr Chapter20ChapterDataChapterDataTableEntry
  .addr Chapter21ChapterDataChapterDataTableEntry
  .addr Chapter21xChapterDataChapterDataTableEntry
  .addr Chapter22ChapterDataChapterDataTableEntry
  .addr Chapter23ChapterDataChapterDataTableEntry
  .addr Chapter24ChapterDataChapterDataTableEntry
  .addr Chapter24xChapterDataChapterDataTableEntry
  .addr ChapterFinalChapterDataChapterDataTableEntry
  .addr ChapterUnknownChapterDataChapterDataTableEntry
  .addr WorldMapChapterDataChapterDataTableEntry
