
aEventTestMapSelectNames ; 82/82BD
  .word <>menutextEventTestMap02
  .word <>menutextEventTestMap02x
  .word <>menutextEventTestMap03
  .word <>menutextEventTestMap04
  .word <>menutextEventTestMap04x
  .word <>menutextEventTestMap05
  .word <>menutextEventTestMap06
  .word <>menutextEventTestMap07
  .word <>menutextEventTestMap08
  .word <>menutextEventTestMap08x
  .word <>menutextEventTestMap09
  .word <>menutextEventTestMap10
  .word <>menutextEventTestMap11
  .word <>menutextEventTestMap11x
  .word <>menutextEventTestMap12
  .word <>menutextEventTestMap12x
  .word <>menutextEventTestMap13
  .word <>menutextEventTestMap14
  .word <>menutextEventTestMap14x
  .word <>menutextEventTestMap15
  .word <>menutextEventTestMap16A
  .word <>menutextEventTestMap17A
  .word <>menutextEventTestMap16B
  .word <>menutextEventTestMap17B
  .word <>menutextEventTestMap18
  .word <>menutextEventTestMap19
  .word <>menutextEventTestMap20
  .word <>menutextEventTestMap21
  .word <>menutextEventTestMap21x
  .word <>menutextEventTestMap22
  .word <>menutextEventTestMap23
  .word <>menutextEventTestMap24
  .word <>menutextEventTestMap24x
  .word <>menutextEventTestMap25
  .word <>menutextEventTestWorldMap
