
aItemNamePointerTable ; B0/8FC3
  .word None
  .addr menutextIronSwordName
  .addr menutextSteelSwordName
  .addr menutextSilverSwordName
  .addr menutextSlimSwordName
  .addr menutextIronBladeName
  .addr menutextKillingEdgeName
  .addr menutextPoisonSwordName
  .addr menutextBerserkSwordName
  .addr menutextSleepSwordName
  .addr menutextBeoBladeName
  .addr menutextBlessedSwordName
  .addr menutextLoptyrsBladeName
  .addr menutextBragisBladeName
  .addr menutextLightBrandName
  .addr menutextBraveSwordName
  .addr menutextSwordOfKingsName
  .addr menutextEarthSwordName
  .addr menutextWindSwordName
  .addr menutextFireBrandName
  .addr menutextVoltEdgeName
  .addr menutextParagonSwordName
  .addr menutextArmorslayerName
  .addr menutextRapierName
  .addr menutextShortswordName
  .addr menutextLongswordName
  .addr menutextGreatswordName
  .addr menutextMasterSwordName
  .addr menutextDarkEdgeName
  .addr menutextMareetasBladeName
  .addr menutextBrokenSwordName
  .addr menutextIronLanceName
  .addr menutextSteelLanceName
  .addr menutextSilverLanceName
  .addr menutextSlimLanceName
  .addr menutextPoisonSpearName
  .addr menutextWyrmlanceName
  .addr menutextDarkLanceName
  .addr menutextBraveLanceName
  .addr menutextShortLanceName
  .addr menutextLongLanceName
  .addr menutextGreatlanceName
  .addr menutextJavelinName
  .addr menutextMasterLanceName
  .addr menutextHorseslayerName
  .addr menutextKillerLanceName
  .addr menutextGaeBolgName
  .addr menutextGungnirName
  .addr menutextBrokenLanceName
  .addr menutextIronAxeName
  .addr menutextPoisonAxeName
  .addr menutextSteelAxeName
  .addr menutextSilverAxeName
  .addr menutextHandAxeName
  .addr menutextHammerName
  .addr menutextKillerAxeName
  .addr menutextPugiName
  .addr menutextBraveAxeName
  .addr menutextDevilAxeName
  .addr menutextBattleAxeName
  .addr menutextHalberdName
  .addr menutextMasterAxeName
  .addr menutextBrokenAxeName
  .addr menutextIronBowName
  .addr menutextSteelBowName
  .addr menutextSilverBowName
  .addr menutextPoisonBowName
  .addr menutextKillerBowName
  .addr menutextBraveBowName
  .addr menutextShortbowName
  .addr menutextLongbowName
  .addr menutextGreatbowName
  .addr menutextMasterBowName
  .addr menutextBallistaName
  .addr menutextIronBallistaName
  .addr menutextKillerBallistaName
  .addr menutextPoisonBallistaName
  .addr menutextBrokenBowName
  .addr menutextFireName
  .addr menutextElfireName
  .addr menutextBolganoneName
  .addr menutextValflameName
  .addr menutextThunderName
  .addr menutextDimevoltName
  .addr menutextThoronName
  .addr menutextMjolnirName
  .addr menutextWindName
  .addr menutextGrafcaliburName
  .addr menutextTornadoName
  .addr menutextForsetiName
  .addr menutextLightName
  .addr menutextNosferatuName
  .addr menutextAuraName
  .addr menutextJormungandName
  .addr menutextFenrirName
  .addr menutextHelName
  .addr menutextLoptyrName
  .addr menutextMeteorName
  .addr menutextBoltingName
  .addr menutextBlizzardName
  .addr menutextVeninName
  .addr menutextStoneName
  .addr menutextForsetiInfiniteName
  .addr menutextDrainedTomeName
  .addr menutextHealName
  .addr menutextMendName
  .addr menutextRecoverName
  .addr menutextPhysicName
  .addr menutextFortifyName
  .addr menutextRescueName
  .addr menutextWarpName
  .addr menutextRestoreName
  .addr menutextSilenceStaffName
  .addr menutextSleepName
  .addr menutextTorchStaffName
  .addr menutextReturnName
  .addr menutextHammerneName
  .addr menutextThiefStaffName
  .addr menutextWatchName
  .addr menutextBerserkName
  .addr menutextUnlockName
  .addr menutextWardName
  .addr menutextRewarpName
  .addr menutextKiaName
  .addr menutextDrainedStaffName
  .addr menutextLuckRingName
  .addr menutextLifeRingName
  .addr menutextSpeedRingName
  .addr menutextMagicRingName
  .addr menutextStrengthRingName
  .addr menutextBodyRingName
  .addr menutextShieldRingName
  .addr menutextSkillRingName
  .addr menutextLegRingName
  .addr menutextKnightCrestName
  .addr menutextMasterSealName
  .addr menutextChestKeyName
  .addr menutextDoorKeyName
  .addr menutextBridgeKeyName
  .addr menutextLockpickName
  .addr menutextStaminaDrinkName
  .addr menutextVulneraryName
  .addr menutextPureWaterName
  .addr menutextTorchName
  .addr menutextAntidoteName
  .addr menutextMemberCardName
  .addr menutextOdosScrollName
  .addr menutextBaldursScrollName
  .addr menutextHezulsScrollName
  .addr menutextDainsScrollName
  .addr menutextNovasScrollName
  .addr menutextNeirsScrollName
  .addr menutextUllursScrollName
  .addr menutextTordosScrollName
  .addr menutextValasScrollName
  .addr menutextCedsScrollName
  .addr menutextBragisScrollName
  .addr menutextHeimsScrollName
  .addr menutextParagonManualName
  .addr menutextAssailManualName
  .addr menutextBargainManualName
  .addr menutextVantageManualName
  .addr menutextWrathManualName
  .addr menutextAdeptManualName
  .addr menutextMiracleManualName
  .addr menutextNihilManualName
  .addr menutextSolManualName
  .addr menutextLunaManualName
