
structBattleQuoteEntry .struct Character, Chapter, Flag, DialoguePointer
	.sint \Character
	.char \Chapter
	.byte \Flag
	.long \DialoguePointer
	.ends

structRetreatQuoteEntry .struct Character, Chapter, Flag, DialoguePointer
	.sint \Character
	.char \Chapter
	.byte \Flag
	.long \DialoguePointer
	.ends

structReleaseQuoteEntry .struct Character, Chapter, Flag, DialoguePointer
	.sint \Character
	.char \Chapter
	.byte \Flag
	.long \DialoguePointer
	.ends

structDeathQuoteEntry .struct Character, Chapter, Flag, DialoguePointer
	.sint \Character
	.char \Chapter
	.byte \Flag
	.long \DialoguePointer
	.ends
