
.weak
  WARNINGS :?= "None"
.endweak

GUARD_FE5_CHAPTER_DIALOGUE_POINTERS :?= false
.if (!GUARD_FE5_CHAPTER_DIALOGUE_POINTERS)
  GUARD_FE5_CHAPTER_DIALOGUE_POINTERS := true

  ; Freespace inclusions

    .section ChapterDialoguePointersSection

      aChapterDialoguePointers .block ; 82/DB8A
        .long dialogueChapter01Opening1
        .long dialogueChapter01Opening2
        .long dialogueWeissmannBattleQuote
        .long dialogueWeissmannDeathQuote
        .long dialogueWeissmannReleaseQuote
        .long dialogueChapter01Opening3
        .long dialogueChapter01Opening4
        .long dialogueChapter01DagdarArrive1
        .long dialogueChapter01DagdarArrive2
        .long dialogueChapter01EyvelDagdarTalk
        .long dialogueChapter01OrsinTanyaTalk
        .long dialogueChapter01Ending1A
        .long dialogueChapter01OrsinHouseOrsin
        .long dialogueChapter01OrsinHouseOther
        .long dialogueChapter01UnusedHouseYouth
        .long dialogueChapter01HalvanHouseHalvan
        .long dialogueChapter01HalvanHouseOther
        .long dialogueChapter01VulneraryHouse
        .long dialogueChapter01UnusedHouseGirlSecond
        .long dialogueChapter01LifeRingHouse
        .long dialogueChapter01UnusedHouseGirl
        .long dialogueChapter01IronSwordHouse
        .long dialogueChapter01UnusedHouseElder
        .long dialogueChapter01Ending1B
        .long dialogueChapter01UnusedBlank
        .long dialogueChapter02Opening1
        .long dialogueChapter02Opening2A
        .long dialogueChapter02UnusedJabalPlaceholder
        .long dialogueChapter02VulneraryHouse
        .long dialogueChapter02VulneraryHouseVillageAttacked
        .long dialogueChapter02RonanHouse
        .long dialogueChapter02RonanHouseVillageAttacked
        .long dialogueChapter02SpeedRingHouse
        .long dialogueChapter02SpeedRingHouseVillageAttacked
        .long dialogueChapter02Ending1B
        .long dialogueChapter02Ending1A
        .long dialogueBakstBattleQuote
        .long dialogueBakstDeathQuote
        .long dialogueBakstReleaseQuote
        .long dialogueChapter02Opening2B
        .long dialogueChapter02Opening2C
        .long dialogueChapter02xOpening1
        .long dialogueChapter02xOpening2
        .long dialogueChapter02xReinforcementsDialogue
        .long dialogueChapter02xLeifEyvelTalk
        .long dialogueShiva1BattleQuote
        .long dialogueLithisBattleQuote
        .long dialogueShiva1DeathQuote
        .long dialogueShiva1ReleaseQuote
        .long dialogueLithis2DeathQuote
        .long dialogueLithisReleaseQuote
        .long dialogueChapter02xEnding1
        .long dialogueChapter02xEnding2
        .long dialogueChapter03Opening1
        .long dialogueChapter03Opening2
        .long dialogueChapter03RomeoHouseRomeo
        .long dialogueChapter03RomeoHouseOther
        .long dialogueChapter03LuciaHouseLucia
        .long dialogueChapter03LuciaHouseOther
        .long dialogueChapter03HubertHouseHubert
        .long dialogueChapter03HubertHouseOther
        .long dialogueChapter03CairpreHouseCairpre
        .long dialogueChapter03CairpreHouseOther
        .long dialogueLobosBattleQuote
        .long dialogueLobosDeathQuote
        .long dialogueLobosReleaseQuote
        .long dialogueChapter03Ending1
        .long dialogueChapter03Ending2
        .long dialogueChapter03UnusedEndingFinn
        .long dialogueChapter03Ending3
        .long dialogueChapter03Ending5
        .long dialogueChapter03Ending4
        .long dialogueChapter03Ending6
        .long dialogueChapter03Ending7
        .long dialogueChapter04Opening1
        .long dialogueChapter04LeifDialogue
        .long dialogueChapter04Opening2
        .long dialogueChapter04Opening3
        .long dialogueDahlsonBattleQuote
        .long dialogueDahlsonUnusedDeathQuote
        .long dialogueDahlsonReleaseQuote
        .long dialogueChapter04Ending
        .long dialogueChapter04DahlsonRecruitment
        .long dialogueChapter04LithisDialogue
        .long dialogueChapter04NPCDialogue
        .long dialogueChapter04LithisCellUnlock
        .long dialogueChapter04UnusedLeifCellUnlock
        .long dialogueChapter04LeifCellUnlock
        .long dialogueChapter04LeftCellUnlock
        .long dialogueChapter04RightCellUnlock
        .long dialogueChapter04xOpening1
        .long dialogueChapter04xAsvelRecruitment
        .long dialogueChapter04xUnusedBlank
        .long dialogueChapter04xUnusedBattleQuote
        .long dialogueChapter04xUnusedDeathQuote
        .long dialogueChapter04xUnusedReleaseQuote
        .long dialogueChapter04xKarinCedTalk
        .long dialogueChapter04xOpening2
        .long dialogueChapter04xLowerCellUnlock
        .long dialogueChapter04xUpperCellUnlock
        .long dialogueChapter05UnusedRemovedMagicSword
        .long dialogueChapter05Opening1
        .long dialogueChapter05Opening2
        .long dialogueChapter05RaydrikDialogue
        .long dialogueChapter05MareetaAppears1
        .long dialogueChapter05MareetaAppears2
        .long dialogueChapter05MareetaAppears3
        .long dialogueChapter05MareetaAppears4
        .long dialogueChapter05MareetaDialogue
        .long dialogueChapter05MareetaCaptured
        .long dialogueChapter05MareetaKilled
        .long dialogueChapter05ArenaOpen3
        .long dialogueChapter05ArenaOpen1A
        .long dialogueChapter05ArenaOpen1B
        .long dialogueChapter05ArenaOpen1C
        .long dialogueChapter05ArenaOpen2
        .long dialogueChapter05EyvelStone1A
        .long dialogueChapter05EyvelStone2
        .long dialogueChapter05EyvelStone3
        .long dialogueChapter05RaydrikPlaceholder
        .long dialogueChapter05FinnPlaceholder
        .long dialogueNannaChapter05RetreatQuote
        .long dialogueLeifChapter05RetreatQuote
        .long dialogueChapter05ArenaOpen1D
        .long dialogueChapter05EyvelStone1B
        .long dialogueChapter05ArenaOpen1E
        .long dialogueChapter05ArenaOpenAfterStone
        .long dialogueMareetaChapter05DeathQuote
        .long dialogueChapter06Opening1
        .long dialogueChapter06Opening2
        .long dialogueChapter06UnusedRemovedShivaSapphie
        .long dialogueChapter06GalzusSpawn
        .long dialogueChapter06UnusedCodhaRaydrik
        .long dialogueChapter06KnightCrestHouseEmilyAlive
        .long dialogueChapter06KnightCrestHouseEmilyDead
        .long dialogueChapter06HicksHouseMuffyAlive
        .long dialogueChapter06HicksHouseMuffyDead
        .long dialogueChapter06PureWaterHouseVeraAlive
        .long dialogueChapter06PureWaterHouseVeraDead
        .long dialogueChapter06RapierHouseCliffAlive
        .long dialogueChapter06RapierHouseCliffDead
        .long dialogueChapter06ParagonManualHouseBowieAlive
        .long dialogueChapter06ParagonManualHouseBowieDead
        .long dialogueChapter06OdosScrollHouseLinaAlive
        .long dialogueChapter06OdosScrollHouseLinaDead
        .long dialogueChapter06Ending
        .long dialogueShiva2BattleQuote
        .long dialogueShiva2DeathQuote
        .long dialogueShiva2ReleaseQuote
        .long dialogueGalzusBattleQuote
        .long dialogueChapter06DoorOpenDialogue1
        .long dialogueChapter06DoorOpenDialogue2
        .long dialogueChapter06CedArrive
        .long dialogueChapter06CedLeave
        .long dialogueChapter07Opening1
        .long dialogueChapter07EisenhoweSpawn
        .long dialogueChapter07FinnSapphieAppear1
        .long dialogueChapter07FinnSapphieAppear2
        .long dialogueChapter07FinnSapphieAppear3
        .long dialogueChapter07HannibalAppear
        .long dialogueChapter07RaydrikDialogue
        .long dialogueChapter07Ending1
        .long dialogueChapter07Ending2
        .long dialogueChapter07Ending3
        .long dialogueChapter07Ending4
        .long dialogueChapter07Ending5
        .long dialogueChapter07HannibalLoad
        .long dialogueChapter07Ending6
        .long dialogueChapter07Ending7
        .long dialogueChapter07Ending8
        .long dialogueChapter07Ending9
        .long dialogueEisenhoweBattleQuote
        .long dialogueEisenhoweDeathQuote
        .long dialogueEisenhoweReleaseQuote
        .long dialogueRaydrikBattleQuote
        .long dialogueChapter07UnusedDeathQuote
        .long dialogueChapter07Opening2
        .long dialogueChapter07SapphieShivaTalk
        .long dialogueChapter07FinnSapphieAppear4A
        .long dialogueChapter07FinnSapphieAppear5
        .long dialogueChapter06SaiasGalzus1
        .long dialogueChapter06SaiasGalzus2
        .long dialogueChapter07FinnSapphieAppear4B
        .long dialogueChapter07LeifFinnTalk
        .long dialogueChapter07NannaFinnTalk
        .long dialogueChapter07AntidoteHouse
        .long dialogueChapter07KnightCrestHouse
        .long dialogueChapter07EmilyFailurePlaceholder
        .long dialogueChapter07PureWaterHouse
        .long dialogueChapter08Opening1
        .long dialogueChapter08GomerAppear
        .long dialogueChapter08KnightCrestHouse
        .long dialogueChapter08LuckRingHouse
        .long dialogueChapter08TanyaPlaceholder
        .long dialogueChapter08GomerPlaceholder
        .long dialogueChapter08RumaighMount
        .long dialogueChapter08Ending1A
        .long dialogueChapter08Ending1B
        .long dialogueRumaighBattleQuote
        .long dialogueRumaighDeathQuote
        .long dialogueRumaighReleaseQuote
        .long dialogueMartyBattleQuote
        .long dialogueMartyChapter08DeathQuote
        .long dialogueChapter08MartyCaptured
        .long dialogueChapter08UnusedDagdarPlaceholder
        .long dialogueChapter08UnusedHouse1
        .long dialogueChapter08UnusedHouse2
        .long dialogueChapter08OrsinMartyTalk
        .long dialogueChapter08HalvanMartyTalk
        .long dialogueChapter08Ending1D
        .long dialogueChapter08Ending1C
        .long dialogueChapter08xOpening1
        .long dialogueChapter08xOrsinTanyaTalk
        .long dialogueChapter08xLeifDagdarTalk
        .long dialogueChapter08xEnding1
        .long dialogueGomerBattleQuote
        .long dialogueGomerDeathQuote
        .long dialogueGomerReleaseQuote
        .long dialogueChapter08xOpeningPlaceholder
        .long dialogueSigurdPlaceholderDeathQuote
        .long dialogueLeifDeathQuote
        .long dialogueFinnDeathQuote
        .long dialogueOrsinDeathQuote
        .long dialogueHalvanDeathQuote
        .long dialogueEyvelDeathQuote
        .long dialogueDagdarDeathQuote
        .long dialogueRalphDeathQuote
        .long dialogueMartyDeathQuote
        .long dialogueRonanDeathQuote
        .long dialogueMirandaDeathQuote
        .long dialogueSapphieDeathQuote
        .long dialogueLaraDeathQuote
        .long dialogueBrightonDeathQuote
        .long dialogueFergusDeathQuote
        .long dialogueEdaDeathQuote
        .long dialogueAsvelDeathQuote
        .long dialogueMatriaDeathQuote
        .long dialogueHicksDeathQuote
        .long dialogueNannaDeathQuote
        .long dialogueSelphinaDeathQuote
        .long dialogueDahlsonDeathQuote
        .long dialogueCallionDeathQuote
        .long dialogueGalzus1DeathQuote
        .long dialoguePanDeathQuote
        .long dialogueGladeDeathQuote
        .long dialogueKaneDeathQuote
        .long dialogueAlbaDeathQuote
        .long dialogueRobertDeathQuote
        .long dialogueFredDeathQuote
        .long dialogueOlwenDeathQuote
        .long dialogueCedDeathQuote
        .long dialogueLithis1DeathQuote
        .long dialogueKarinDeathQuote
        .long dialogueDeanDeathQuote
        .long dialogueShanam2DeathQuote
        .long dialogueTrudeDeathQuote
        .long dialogueTanyaDeathQuote
        .long dialogueLinoanDeathQuote
        .long dialogueMischaDeathQuote
        .long dialogueSalemDeathQuote
        .long dialogueSchroffDeathQuote
        .long dialogueMareetaDeathQuote
        .long dialogueTinaDeathQuote
        .long dialogueGunterDeathQuote
        .long dialogueAmaldaDeathQuote
        .long dialogueConomoreDeathQuote
        .long dialogueHomerDeathQuote
        .long dialogueDermottDeathQuote
        .long dialogueSarahDeathQuote
        .long dialogueSaiasDeathQuote
        .long dialogueUnknownUnusedDeathQuote
        .long dialogueLeifDeathNanna
        .long dialogueLeifDeathFinn
        .long dialogueLeifDeathEyvel
        .long dialogueLeifDeathDorias
        .long dialogueLeifDeathAugust
        .long dialogueLeifUnusedRetreatQuote
        .long dialogueFinnRetreatQuote
        .long dialogueOrsinRetreatQuote
        .long dialogueHalvanRetreatQuote
        .long dialogueEyvelRetreatQuote
        .long dialogueDagdarRetreatQuote
        .long dialogueRalphRetreatQuote
        .long dialogueMartyRetreatQuote
        .long dialogueRonanRetreatQuote
        .long dialogueMirandaRetreatQuote
        .long dialogueSapphieRetreatQuote
        .long dialogueLaraRetreatQuote
        .long dialogueBrightonRetreatQuote
        .long dialogueFergusRetreatQuote
        .long dialogueEdaRetreatQuote
        .long dialogueAsvelRetreatQuote
        .long dialogueMatriaRetreatQuote
        .long dialogueHicksRetreatQuote
        .long dialogueNannaRetreatQuote
        .long dialogueSelphinaRetreatQuote
        .long dialogueDahlsonRetreatQuote
        .long dialogueCallionRetreatQuote
        .long dialogueGalzusRetreatQuote
        .long dialoguePanRetreatQuote
        .long dialogueGladeRetreatQuote
        .long dialogueKaneRetreatQuote
        .long dialogueAlbaRetreatQuote
        .long dialogueRobertRetreatQuote
        .long dialogueFredRetreatQuote
        .long dialogueOlwenRetreatQuote
        .long dialogueCed1RetreatQuote
        .long dialogueCed2RetreatQuote
        .long dialogueLithisRetreatQuote
        .long dialogueKarinRetreatQuote
        .long dialogueDeanRetreatQuote
        .long dialogueShanamRetreatQuote
        .long dialogueTrudeRetreatQuote
        .long dialogueTanyaRetreatQuote
        .long dialogueLinoanRetreatQuote
        .long dialogueMischaRetreatQuote
        .long dialogueSalemRetreatQuote
        .long dialogueSchroffRetreatQuote
        .long dialogueMareetaRetreatQuote
        .long dialogueTinaRetreatQuote
        .long dialogueGunterRetreatQuote
        .long dialogueAmaldaRetreatQuote
        .long dialogueConomoreRetreatQuote
        .long dialogueHomerRetreatQuote
        .long dialogueDermottRetreatQuote
        .long dialogueSarahRetreatQuote
        .long dialogueSaiasRetreatQuote
        .long dialogueShivaRetreatQuote
        .long dialogueXavierRetreatQuote
        .long dialogueIliosRetreatQuote
        .long dialogueChapterEndLinoanDead
        .long dialogueChapter09Opening1
        .long dialogueChapter09Opening2
        .long dialogueChapter09Opening3
        .long dialogueChapter09LeifSelphinaTalk
        .long dialogueChapter09SelphinaFinnTalk1
        .long dialogueChapter09SelphinaFinnTalk2
        .long dialogueChapter09Ending1
        .long dialogueMerlochBattleQuote
        .long dialogueMerlochDeathQuote
        .long dialogueMerlochReleaseQuote
        .long dialogueChapter09PlayerLoss
        .long dialogueChapter09Ending2
        .long dialogueChapter09Ending3
        .long dialogueChapter09ValasScrollHouse
        .long dialogueChapter09StaminaDrinkHouse
        .long dialogueChapter09UnusedMerloch1
        .long dialogueChapter09UnusedMerloch2
        .long dialogueChapter09CallionSelphinaTalk
        .long dialogueChapter10Opening1
        .long dialogueChapter10Opening2
        .long dialogueChapter10OlwenFredArrive
        .long dialogueChapter10OlwenFredLeave
        .long dialogueChapter10Ending1A
        .long dialogueChapter10Ending1B
        .long dialogueLargoBattleQuote
        .long dialogueLargoDeathQuote
        .long dialogueLargoReleaseQuote
        .long dialogueOlwenChapter10BattleQuote
        .long dialogueFredChapter10BattleQuote
        .long dialogueFredChapter10DeathQuote
        .long dialogueFredUnusedChapter10ReleaseQuote
        .long dialogueChapter10UnusedSaiasMareetaPlaceholder
        .long dialogueChapter10UnusedNotNannaPlaceholder
        .long dialogueChapter10UnusedNannaPlaceholder
        .long dialogueChapter10RescueHouse
        .long dialogueChapter10WardHouse
        .long dialogueChapter10UnusedHouse
        .long dialogueChapter10UnusedOlwenWeaponless
        .long dialogueChapter10UnusedFredWeaponless
        .long dialogueChapter11Opening1
        .long dialogueChapter11Opening2
        .long dialogueChapter11Opening3
        .long dialogueChapter11KempfDialogue
        .long dialogueKempfChapter11BattleQuote
        .long dialogueChapter11KempfLeave
        .long dialogueChapter11Ending1A
        .long dialogueChapter11Ending1B
        .long dialogueFredBattleQuote
        .long dialogueFredChapter11DeathQuote
        .long dialogueFredReleaseQuote
        .long dialogueChapter11FredChange
        .long dialogueChapter11TrapSprung
        .long dialogueChapter11xOpening1
        .long dialogueChapter11xOpening2
        .long dialogueChapter11xFredArrive
        .long dialogueChapter11xLeifOlwenTalk
        .long dialogueChapter11xFredOlwenTalk
        .long dialogueChapter11xEnding1
        .long dialogueChapter11xEnding2
        .long dialogueHortefeuxBattleQuote
        .long dialogueHortefeuxDeathQuote
        .long dialogueHortefeuxReleaseQuote
        .long dialogueChapter11xUnusedOlwenFredTalk
        .long dialogueChapter11xHortefeuxLeave
        .long dialogueChapter12Opening1
        .long dialogueChapter12KolkhoDialogue
        .long dialogueChapter12GaidenFailDialogue
        .long dialogueChapter12SalemDialogue
        .long dialogueChapter12Ending1A
        .long dialogueChapter12Ending1B
        .long dialogueChapter12RosaHouseRosaAlive
        .long dialogueChapter12RosaHouseOlwen
        .long dialogueChapter12RosaHouseRosaDead
        .long dialogueChapter12HeimsScrollHouseSaylaAlive
        .long dialogueChapter12HeimsScrollHouseSaylaDead
        .long dialogueChapter12SilenceHousePeterAlive
        .long dialogueChapter12SilenceHousePeterDead
        .long dialogueChapter12UnusedHouseAlive
        .long dialogueChapter12UnusedHouseDead
        .long dialogueSalemBattleQuote
        .long dialogueChapter12UnusedSalemAlternate
        .long dialogueSalemChapter12DeathQuote
        .long dialogueSalemReleaseQuote
        .long dialogueKolkhoBattleQuote
        .long dialogueKolkhoDeathQuote
        .long dialogueKolkhoReleaseQuote
        .long dialogueChapter12Opening2
        .long dialogueChapter12MareetaDialogue
        .long dialogueChapter12Ending2
        .long dialogueChapter12xOpening1
        .long dialogueChapter12xOpening2
        .long dialogueChapter12xOpening3
        .long dialogueChapter12xOpening4
        .long dialogueChapter12xPanRecruitment1
        .long dialogueChapter12xPanRecruitment2
        .long dialogueChapter12xLithisPanTalk1
        .long dialogueChapter12xLithisPanTalk2
        .long dialogueChapter12xTrudeRecruitment
        .long dialogueChapter12xTinaRecruitment
        .long dialogueChapter12xLaraPanTalk
        .long dialogueChapter12xEnding1
        .long dialogueChapter12xUnusedRemoved
        .long dialogueChapter12xEnding2
        .long dialogueChapter12xEnding3
        .long dialoguePanBattleQuote
        .long dialoguePanChapter12xDeathQuote
        .long dialoguePanReleaseQuote
        .long dialogueTrudeBattleQuote
        .long dialogueTrudeChapter12xDeathQuote
        .long dialogueTrudeReleaseQuote
        .long dialogueTinaBattleQuote
        .long dialogueTinaChapter12xDeathQuote
        .long dialogueTinaReleaseQuote
        .long dialogueChapter13Opening1
        .long dialogueChapter13Opening2
        .long dialogueChapter13Opening3
        .long dialogueChapter13Opening4
        .long dialogueChapter13FinnGladeTalk
        .long dialogueChapter13SelphinaGladeTalk1A
        .long dialogueChapter13SelphinaGladeTalk1B
        .long dialogueChapter13LeifGladeTalk
        .long dialogueChapter13ArmorslayerHouse
        .long dialogueChapter13UnusedBlank1
        .long dialogueChapter13KnightCrestHouse
        .long dialogueChapter13UnusedBlank2
        .long dialogueChapter13HammerHouse
        .long dialogueChapter13Unused
        .long dialogueChapter13Ending1
        .long dialogueChapter13PlayerLoss
        .long dialogueLisztBattleQuote
        .long dialogueLisztDeathQuote
        .long dialogueLisztReleaseQuote
        .long dialogueBaldachChapter13BattleQuote
        .long dialogueBaldachChapter13DeathQuote
        .long dialogueBaldachChapter13ReleaseQuote
        .long dialogueChapter14Opening1
        .long dialogueChapter14Opening2
        .long dialogueChapter14ShanamLeave
        .long dialogueChapter14UnusedRemovedKarinShanam
        .long dialogueChapter14UnusedRemovedLaraTransformation
        .long dialogueChapter14NPCArrive
        .long dialogueChapter14Ending1
        .long dialogueChapter14Ending2
        .long dialoguePaulusBattleQuote
        .long dialoguePaulusDeathQuote
        .long dialoguePaulusReleaseQuote
        .long dialogueBaldachBattleQuote
        .long dialogueBaldachDeathQuote
        .long dialogueBaldachReleaseQuote
        .long dialogueChapter14HomerRecruitment
        .long dialogueChapter14HomerHouseChild
        .long dialogueChapter14HomerHouseMan
        .long dialogueChapter14HomerHouseWoman
        .long dialogueChapter14House1
        .long dialogueChapter14House2
        .long dialogueChapter14House3
        .long dialogueChapter14House4
        .long dialogueChapter14House5
        .long dialogueChapter14House6
        .long dialogueChapter14NosferatuHouse
        .long dialogueChapter14WyrmlanceHouseOther
        .long dialogueChapter14WyrmlanceHouseDean
        .long dialogueChapter14xOpening1
        .long dialogueChapter14xOpening2
        .long dialogueChapter14xCivilian1
        .long dialogueChapter14xCivilian2
        .long dialogueChapter14xCivilian3
        .long dialogueChapter14xCivilian4
        .long dialogueChapter14xCivilian5
        .long dialogueChapter14xCivilian6
        .long dialogueChapter14xEnding1
        .long dialogueChapter14xUnusedFailurePlaceholder
        .long dialogueCodhaBattleQuote
        .long dialogueCodhaDeathQuote
        .long dialogueCodhaReleaseQuote
        .long dialogueChapter15Opening1
        .long dialogueChapter15Opening2
        .long dialogueChapter15RalphAmaldaArrive
        .long dialogueChapter15ChurchLeif1
        .long dialogueChapter15UnusedBlank1
        .long dialogueChapter15UnusedBlank2
        .long dialogueChapter15UnusedBlank3
        .long dialogueChapter15ChurchLeif2
        .long dialogueChapter15ChurchLeif3
        .long dialogueChapter15ChurchOther
        .long dialogueChapter15ArmorslayerHouse
        .long dialogueChapter15SkillRingHouse
        .long dialogueChapter15KillerLanceHouse
        .long dialogueChapter15UllursScrollHouse
        .long dialogueChapter15LeftPath
        .long dialogueChapter15LeftPathConfirm
        .long dialogueChapter15RightPath
        .long dialogueChapter15RightPathConfirm
        .long dialogueZailleBattleQuote
        .long dialogueZailleDeathQuote
        .long dialogueZailleReleaseQuote
        .long dialogueChapter15RalphRecruitment
        .long dialogueChapter15AmaldaFlee
        .long dialogueChapter16AOpening1
        .long dialogueChapter16AOpening2
        .long dialogueChapter16AOpening3
        .long dialogueChapter16AOlwenKempfTalk
        .long dialogueChapter16AKempfCharge
        .long dialogueChapter16AConomoreArrive
        .long dialogueChapter16ASchroffDialogue
        .long dialogueChapter16AConomoreFlee
        .long dialogueChapter16AIliosComplaint
        .long dialogueChapter16AIliosRecruitment
        .long dialogueChapter16ASchroffHouseLeif
        .long dialogueChapter16ASchroffHouseOther
        .long dialogueChapter16ABridgeKeyHouse
        .long dialogueChapter16APureWaterHouse
        .long dialogueChapter16AKnightCrestHouse
        .long dialogueChapter16AEnding1
        .long dialogueChapter16AEnding2
        .long dialogueChapter16AEnding3
        .long dialogueKempfBattleQuote
        .long dialogueChapter16AUnusedBattleQuote
        .long dialogueKempfDeathQuote
        .long dialogueKempfReleaseQuote
        .long dialogueBrooksBattleQuote
        .long dialogueBrooksDeathQuote
        .long dialogueBrooksReleaseQuote
        .long dialogueIliosBattleQuote
        .long dialogueIliosBattleQuote
        .long dialogueIliosDeathQuote
        .long dialogueIliosDeathQuote
        .long dialogueIliosReleaseQuote
        .long dialogueIliosReleaseQuote
        .long dialogueConomoreChapter16ABattleQuote
        .long dialogueConomoreChapter16AReleaseQuote
        .long dialogueNicolovBattleQuote
        .long dialogueNicolovDeathQuote
        .long dialogueNicolovReleaseQuote
        .long dialogueChapter17AOpening1
        .long dialogueChapter17AOpening2
        .long dialogueChapter17AOpening3
        .long dialogueChapter17ASaiasSpawn1A
        .long dialogueChapter17ASaiasSpawn1B
        .long dialogueChapter17ASaiasSpawn2
        .long dialogueChapter17AMuellerSpawn
        .long dialogueChapter17ASaiasLeave
        .long dialogueChapter17AKarinMischaTalk
        .long dialogueChapter17AUnusedBridgeLower
        .long dialogueChapter17AUnusedBridgeRaise
        .long dialogueChapter17AMemberCardPlaceholder
        .long dialogueChapter17AKnightCrestPlaceholder
        .long dialogueChapter17AEnding1
        .long dialogueChapter17AEnding2
        .long dialogueMooreBattleQuote
        .long dialogueMooreDeathQuote
        .long dialogueMooreReleaseQuote
        .long dialogueMuellerBattleQuote
        .long dialogueMuellerDeathQuote
        .long dialogueMuellerReleaseQuote
        .long dialogueSaias1BattleQuote
        .long dialogueSaias1ReleaseQuote
        .long dialogueMischaBattleQuote
        .long dialogueMischaReleaseQuote
        .long dialogueSarahBattleQuote
        .long dialogueSarahReleaseQuote
        .long dialogueChapter17ARescueHouse
        .long dialogueChapter17AWarpHouse
        .long dialogueChapter17APureWaterHouse
        .long dialogueChapter17AMagicRingHouse
        .long dialogueChapter17AChurch
        .long dialogueChapter16BOpening1
        .long dialogueChapter16BOpening2
        .long dialogueChapter16BHomerShanamTalk
        .long dialogueChapter16BMirandaDialogue
        .long dialogueChapter16BLeifSarahTalk
        .long dialogueChapter16BSalemSarahTalk
        .long dialogueChapter16BSarahArrive
        .long dialogueChapter16BUnusedMemberCardPlaceholder
        .long dialogueChapter15MareetaAstra1
        .long dialogueChapter15MareetaAstra2
        .long dialogueChapter16BUnusedKnightCrestPlaceholder
        .long dialogueChapter16BEnding1
        .long dialogueReinkochBattleQuote
        .long dialogueReinkochDeathQuote
        .long dialogueReinkochReleaseQuote
        .long dialogueShanamBattleQuote
        .long dialogueShanam1DeathQuote
        .long dialogueShanamReleaseQuote
        .long dialogueChapter16BHouse
        .long dialogueChapter17BOpening1
        .long dialogueChapter17BOpening2
        .long dialogueChapter17BLowerGateOpen
        .long dialogueChapter17BGateTurn2Placeholder
        .long dialogueChapter17BGateTurn3Placeholder
        .long dialogueChapter17BGateTurn4Placeholder
        .long dialogueChapter17BAmaldaCharge
        .long dialogueChapter17BNPCHousesLeif
        .long dialogueChapter17BNPCHousesOther
        .long dialogueChapter17BNPCHousesPrompt
        .long dialogueChapter17BGateHouse
        .long dialogueChapter17BGateHouseCannotAfford
        .long dialogueChapter17BGateHousePrompt
        .long dialogueChapter17BEnding1
        .long dialogueChapter17BEnding2
        .long dialogueParmannBattleQuote
        .long dialogueParmannDeathQuote
        .long dialogueParmannReleaseQuote
        .long dialogueAmaldaChapter17BBattleQuote
        .long dialogueAmaldaChapter17BReleaseQuote
        .long dialogueChapter18Opening1
        .long dialogueChapter18Opening2
        .long dialogueChapter18Ending1
        .long dialogueChapter18Ending2
        .long dialogueChapter18Ending3A
        .long dialogueChapter18Ending3B
        .long dialogueChapter18Ending4
        .long dialogueChapter18Ending5
        .long dialogueXavierBattleQuote
        .long dialogueXavierDeathQuote
        .long dialogueXavierReleaseQuote
        .long dialogueChapter18XavierArmor1
        .long dialogueChapter18XavierArmor2
        .long dialogueChapter18XavierArmor3
        .long dialogueChapter18XavierArmor4
        .long dialogueChapter18XavierArmor5
        .long dialogueChapter18XavierArmor6
        .long dialogueChapter18XavierArmor7
        .long dialogueChapter18XavierArmor8
        .long dialogueChapter18XavierRecruitment
        .long dialogueChapter19Opening1
        .long dialogueChapter19Opening2
        .long dialogueChapter19Opening3A
        .long dialogueChapter19Opening3B
        .long dialogueChapter19UnusedBarath
        .long dialogueChapter19ConomoreRecruitment
        .long dialogueChapter19AmaldaRecruitment
        .long dialogueChapter19UnusedIshtarArrive
        .long dialogueChapter19UnusedIshtarCommand
        .long dialogueChapter19UnusedIshtarLeave
        .long dialogueChapter19PureWater1House
        .long dialogueChapter19SilverSwordHouse
        .long dialogueChapter19KillerLanceHouse
        .long dialogueChapter19SpeedRingHouse
        .long dialogueChapter19PureWater2House
        .long dialogueChapter19Heal1House
        .long dialogueChapter19WardHouse
        .long dialogueChapter19Heal2House
        .long dialogueChapter19WindHouse
        .long dialogueChapter19Ending1
        .long dialogueChapter19UnusedConomoreEnding
        .long dialogueChapter19UnusedAmaldaEnding
        .long dialogueChapter19Ending2
        .long dialogueWolfeChapter19BattleQuote
        .long dialogueWolfeChapter19DeathQuote
        .long dialogueWolfeChapter19ReleaseQuote
        .long dialogueAmaldaBattleQuote
        .long dialogueAmaldaReleaseQuote
        .long dialogueConomoreBattleQuote
        .long dialogueConomoreReleaseQuote
        .long dialogueIshtarBattleQuote
        .long dialogueChapter20Opening1
        .long dialogueChapter20Opening2
        .long dialogueChapter20Opening3
        .long dialogueChapter20UnusedDialogue
        .long dialogueChapter20Ending1
        .long dialogueChapter20Ending2A
        .long dialogueChapter20Ending2B
        .long dialogueChapter20Ending3B
        .long dialogueChapter20UnusedEnding
        .long dialogueChapter20PlayerLoss
        .long dialogueMannheimBattleQuote
        .long dialogueMannheimDeathQuote
        .long dialogueMannheimReleaseQuote
        .long dialogueGustavBattleQuote
        .long dialogueGustavDeathQuote
        .long dialogueGustavReleaseQuote
        .long dialogueBarathBattleQuote
        .long dialogueBarathDeathQuote
        .long dialogueBarathReleaseQuote
        .long dialogueChapter20SilenceHouse
        .long dialogueChapter21Opening1
        .long dialogueChapter21Opening2
        .long dialogueChapter21Opening3
        .long dialogueChapter21Opening4
        .long dialogueChapter21ChurchLinoan
        .long dialogueChapter21ChurchOther
        .long dialogueChapter21PureWaterHouse
        .long dialogueChapter21SilverSwordHouse
        .long dialogueChapter21Ending1B
        .long dialogueChapter21Ending1A
        .long dialogueFlavusBattleQuote
        .long dialogueFlavusDeathQuote
        .long dialogueFlavusReleaseQuote
        .long dialogueSeimtoreBattleQuote
        .long dialogueSeimtoreDeathQuote
        .long dialogueSeimtoreReleaseQuote
        .long dialogueChapter21xOpening1
        .long dialogueChapter21xOpening2
        .long dialogueChapter21xUnused
        .long dialogueChapter21xEnding1
        .long dialogueChapter21xDarkMageReinforcements
        .long dialogueZaummBattleQuote
        .long dialogueZaummDeathQuote
        .long dialogueZaummReleaseQuote
        .long dialogueChapter22Opening4
        .long dialogueChapter22Opening1
        .long dialogueChapter22Opening2
        .long dialogueChapter22Opening3
        .long dialogueChapter22ReinhardtOlwenTalk1
        .long dialogueChapter22ReinhardtOlwenTalk2
        .long dialogueChapter22SaiasLeaveCohenAlive
        .long dialogueChapter22SaiasLeaveCohenDead
        .long dialogueChapter22Approach1A
        .long dialogueChapter22Approach1B
        .long dialogueChapter22Approach2
        .long dialogueChapter22Ending1
        .long dialogueChapter22UnusedSalemPlaceholder
        .long dialogueChapter22PureWaterHouse
        .long dialogueChapter22WarpHouse
        .long dialogueChapter22RescueHouse
        .long dialogueCohenBattleQuote
        .long dialogueCohenDeathQuote
        .long dialogueCohenReleaseQuote
        .long dialogueSaias2BattleQuote
        .long dialogueSaias2ReleaseQuote
        .long dialogueReinhardtBattleQuote
        .long dialogueReinhardtDeathQuote
        .long dialogueReinhardtReleaseQuote
        .long dialogueChapter23Opening1
        .long dialogueChapter23Opening2
        .long dialogueChapter23Opening3
        .long dialogueChapter23CoulterSpawn
        .long dialogueChapter23AltenaLeave
        .long dialogueChapter23CedAppear
        .long dialogueChapter23LeifCedTalk
        .long dialogueChapter23LeifSaiasTalk
        .long dialogueChapter23AlphanFetch
        .long dialogueChapter23AlphanTome
        .long dialogueChapter23Ending1
        .long dialogueChapter23Ending2A
        .long dialogueChapter23Ending2B
        .long dialogueChapter23SaiasLoad
        .long dialogueChapter23Ending2C
        .long dialogueChapter23Ending3
        .long dialogueChapter23Ending4B
        .long dialogueChapter23Ending4A
        .long dialogueChapter23SarahPlaceholder
        .long dialogueCedDeathLeifAugust
        .long dialogueChapter23VulneraryHouse
        .long dialogueChapter23PureWaterHouse
        .long dialogueChapter23PhysicHouse
        .long dialogueChapter23ItemlessHouse2
        .long dialogueChapter23ItemlessHouse1
        .long dialogueCoulterBattleQuote
        .long dialogueCoulterDeathQuote
        .long dialogueCoulterReleaseQuote
        .long dialogueAlphanBattleQuote
        .long dialogueAlphanDeathQuote
        .long dialogueAlphanReleaseQuote
        .long dialogueFardenBattleQuote
        .long dialogueFardenDeathQuote
        .long dialogueFardenReleaseQuote
        .long dialogueChapter24Opening1
        .long dialogueChapter24Opening2A
        .long dialogueChapter24Opening2B
        .long dialogueChapter24Opening2C
        .long dialogueChapter24Opening2D
        .long dialogueChapter24KiaDoor1
        .long dialogueChapter24KiaDoor2
        .long dialogueChapter24MareetaGalzusTalk
        .long dialogueChapter24Ending1
        .long dialogueChapter24Ending2B
        .long dialogueChapter24Ending2A
        .long dialogueRaydrikChapter24BattleQuote
        .long dialogueRaydrikChapter24DeathQuote
        .long dialogueGalzusChapter24DeathQuote
        .long dialogueGalzusReleaseQuote
        .long dialogueChapter24xOpening1
        .long dialogueChapter24xLeifEyvelTalk
        .long dialogueChapter24xMareetaEyvelTalk
        .long dialogueChapter24xEnding1
        .long dialogueChapter24xEnding2
        .long dialogueChapter24xEnding3
        .long dialogueChapter24xEnding4
        .long dialogueChapter24xEnding5
        .long dialogueChapter24xEnding6
        .long dialogueChapter24xEnding7
        .long dialogueChapter24xEnding8
        .long dialogueChapter24xEnding9
        .long dialogueChapterFinalOpening1
        .long dialogueChapterFinalOpening2
        .long dialogueChapterFinalThroneOpen
        .long dialogueChapterFinalEnding1
        .long dialogueChapterFinalEnding2
        .long dialogueChapterFinalEnding3
        .long dialogueChapterFinalEnding4
        .long dialogueChapterFinalEnding5
        .long dialogueChapterFinalEnding6
        .long dialogueChapterFinalEnding7
        .long dialogueChapterFinalUnusedLeifLoad
        .long dialogueChapterFinalNannaLoad
        .long dialogueChapterFinalEnding8
        .long dialogueChapterFinalEnding9
        .long dialogueVeldBattleQuote
        .long dialogueVeldDeathQuote
        .long dialogueVeldReleaseQuote
        .long dialogueChapterFinalUnusedBattleQuote
        .long dialogueChapterFinalUnusedDeathQuote
        .long dialogueChapterFinalUnusedReleaseQuote
      .endblock

    .endsection ChapterDialoguePointersSection

.endif ; GUARD_FE5_CHAPTER_DIALOGUE_POINTERS
